name: wake-up-test
services:
  dev-db:
    image: postgres:15.4
    ports:
      - 5434:5432
    env_file:
      - .env
    networks:
      - wake-up-test-network

  e2e-test-db:
    image: postgres:15.4
    ports:
      - 5435:5432
    env_file:
      - .env.test
    networks:
      - wake-up-test-network

networks:
  wake-up-test-network:
